# Generated by Django 3.2.9 on 2021-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20211205_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='file',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
